name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Install
        if: success()
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: install

      - name: Build
        if: success()
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: build

      - name: Deploy
        if: success()
        uses: SamKirkland/FTP-Deploy-Action@3.0.0
        with:
          ftp-server: ${{ secrets.FTP_DESTINATION }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: public
